tasks:
  -
    info: Configuring VIM directory...
    type: symlink
    source: vim
    destination: ~/.vim
  -
    info: Configuring VIM...
    type: symlink
    source: vim/vimrc
    destination: ~/.vimrc
  -
    info: Configuring Silver Searcher...
    type: symlink
    source: ag/agignore
    destination: ~/.agignore
  -
    info: Configuring Ruby Gems...
    type: symlink
    source: ruby/gemrc
    destination: ~/.gemrc
  -
    info: Configuring tmux...
    type: symlink
    source: tmux/tmux.conf
    destination: ~/.tmux.conf
  -
    info: Configuring global Gitignore...
    type: symlink
    source: git/gitignore
    destination: ~/.gitignore
  -
    info: Configuring rbenv...
    type: symlink
    source: rbenv
    destination: ~/.rbenv
  -
    info: Configuring zsh...
    type: symlink
    source: zsh/zshrc
    destination: ~/.zshrc

