# Show contents of directory after cd-ing into it
chpwd() {
  ls
}

# Warn against *grid*/master  branches
preexec(){
  if [ -d .git ]; then
    branch=$(git symbolic-ref HEAD | cut -d'/' -f3)
    if [[ "$branch" =~ 'grid|master' ]]; then
      echo -e "\e[41m    On grid branch!    \e[0m"
    fi
  fi
}

export ZSH=/Users/michalsapka/.oh-my-zsh
ZSH_THEME="bira"
plugins=(git zsh-syntax-highlighting)
export PATH="/Users/michalsapka/.rbenv/shims:/Users/michalsapka/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:$PATH"
eval "$(rbenv init -)"
source $ZSH/oh-my-zsh.sh

alias grid='RBENV_VERSION=2.3 grid'
alias rubocop='RBENV_VERSION=2.3 rubocop'
alias r='bundle exec rspec'
alias code="cd ~/code"
alias buu="brew update;brew upgrade"
alias todo="vi ~/synced/todo/todo.txt"
alias notes="cd ~/synced/notes"
alias vi="/usr/local/bin/vim"
alias vim="vi"
alias v="vi"
alias gdp="grid deploy"
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
alias rspec="bundle exec rspec"
alias amend="git commit --amend"
alias ct="ctags -R --languages=ruby --exclude=.git --exclude=log ."

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
